{% set name = "papylio" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/papylio-{{ version }}.tar.gz
  sha256: d7187e587427fee9b45d635f0e59ab412338ff3dbefc49b87f87057842b8c3b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }},<3.10
    - numpy >=1.22.4,<1.23
    - matplotlib-base >=3.5,<3.6
    - pathlib2 >=2.3
    - opencv >=4.5,<4.6
    - tabulate >=0.8,<0.9
    - scipy >=1.8,<1.9
    - scikit-image >=0.19,<0.20
    - scikit-learn >=1.0,<1.1
    - pyyaml >=6.0,<6.1
    - pandas >=1.4,<1.5
    - seaborn >=0.11,<0.12
    - openpyxl >=3.0,<3.1
    - nd2reader >=3.3,<3.4
    - xarray >=2023.1,<2023.2
    - netcdf4 >=1.6,<1.7
    - h5netcdf >=1.0,<1.1
    - dask-core >=2023.1,<2024.2
    - dask-image >=2021.12,<2022.0
    - bottleneck >=1.3,<1.4
    - tifffile >=2022.10.10,<2022.11
    - tqdm >=4.63
    - hmmlearn >=0.2.7,<0.2.8
    - pyside2 >=5.13,<5.14
    - numba >=0.56,<0.57
    - pomegranate ==0.14.8
    - matchpoint >=1.0,<1.1
    - objectlist >=1.0,<1.1

test:
  imports:
    - papylio
# Pip check is not executed due to errors related to h5netcdf and pomegranate
# When upgrading these packages, reintroduce pip check.
#  commands:
#    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Chirlmin-Joo-lab/papylio
  summary: Single-molecule fluorescence data extraction and analysis.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://papylio.readthedocs.io/
  dev_url: https://github.com/Chirlmin-Joo-lab/papylio

extra:
  recipe-maintainers:
    - ivoseverins
